name: "Trigger build"
on: workflow_dispatch

jobs:
  check:
    name: Trigger build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_dirty_check: true
          commit_message: "Trigger build"
          commit_options: "--allow-empty"
