name: Linting
on:
  pull_request:

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        version: 2.20.2
        files: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
